### ISSUE TITLE
Honor schema name at time of migration

### ISSUE THREAD

**Issue by shehabghazy** [automatisch/automatisch#1059]
Hi guys

Thanks for your continuous effort , we have our own database which has multiple schemas and has already some tables in schema public, we need to migrate automatisch on the same db but it will cause a conflict in table names in schema public and also it will be some kind of disorganization, so it is better to migrate it on a seperated schema.

I have created a pull request with a small changes for this topic about one week ago with a small modification allowing it to honor schema name, so if there is a database already exists and we need to migrate automatisch's tables on it separately in a specific schema it will be easy by adding DATABASE_SCHEMA to env variables.
so if there is DATABASE_SCHEMA in env variables the migration will consider it, if not it will work nomrally with public schema

https://github.com/automatisch/automatisch/pull/1047

Best regards

**Comment by farukaydin** [comment]
Hey @shehabghazy, thanks again for the feedback. I will review your PR today, and (most likely) it will be merged today.

**Comment by shehabghazy** [comment]
hey @farukaydin .. done

**Comment by shehabghazy** [comment]
hey @farukaydin .. I have allowed edits from maintainers

**Comment by farukaydin** [comment]
I will close this issue since the related PR (#1047) is merged. @shehabghazy, it will be ready to use with the next release. Let us know if you have any other feedback about this topic.
