### ISSUE TITLE
Cannot authenticate to Github

### ISSUE THREAD

**Issue by theogf** [automatisch/automatisch#1062]
It tried to create a connection to Github following the instructions.

I created my app, got my client ID and token however when I set it up in Automatisch I get the following error:

```
{
  "message": "Requires authentication",
  "documentation_url": "https://docs.github.com/rest/reference/users#get-the-authenticated-user"
}
````

Did I miss something?

I managed to get a connection to Todoist without any problems.

**Comment by barinali** [comment]
I have just tested it on my local and it seems to be working with GitHub. 

> I created my app, got my client ID and **token** however when I set it up in Automatisch I get the following error:

A gitHub connection isn't supposed to expect a token. I wonder if you provide the expected values. As described on https://automatisch.io/docs/apps/github/connection, Client ID and Secret should be provided to authenticate against GitHub via the OAuth consent dialog.

**Comment by theogf** [comment]
Sorry wrong wording on my side, I did mean passing the Client ID and secret. I just tried in a different browser where I was not logged in Github. It asked me to login (with 2FA) but once it logged it just gave me a new error

**Comment by barinali** [comment]
@theogf, could you elaborate on the new error you have received? I have tried it once again after revoking access to my authorized application, and it still works on my end.

I'll wrap up my day now. However, if you reach me over Discord <sup>1</sup> (in our community server), I'd be happy to take a closer look at this matter. 

<sup>1</sup> I could try to authenticate against your GitHub OAuth application with a redirect URL to our installation for the sake of investigation. For this, I'd need your Client ID and Secret.

**Comment by theogf** [comment]
Sorry I meant that I got the same error.

Sure I will head up to the Discord!

**Comment by theogf** [comment]
So the issue came from the fact that I was using a reverse proxy and that the hosting of automatisch was at `automatisch.mywebsite.com` but I did not set the correct environment variable for it.

Adding 
```
WEB_APP_URL = https://automatisch.mywebsite.com
```
to the `docker-compose.yml` solved the issue.
