### ISSUE TITLE
Mailchimp Integration

### ISSUE THREAD

**Issue by farazfarid** [automatisch/automatisch#1104]
I would love to see a Mailchimp integration especially in terms of adding tags to a subscribed member

**Comment by berserkwarwolf** [comment]
For an MVP, I would suggest doing these first.

Triggers:

- New Subscriber
- New Unsubscriber
- Email Opened

Actions:

- Create Campaign
- Send Campaign

Afterwards, I would advice focusing on segmentation-related triggers and actions (Tags & Audiences).
