### ISSUE TITLE
Discord not working, OAuth Redirect URL only goes to localhost

### ISSUE THREAD

**Issue by LostOnTheLine** [automatisch/automatisch#1105]
I'm running on a server that doesn't have a local browser. I host the docker container exposed the port 8123 to the local network, I have the ENV `PORT=8123` & `'8123:8123'` for the container Ports, but when I try to add a new Discord Bot Connection, after I `Submit` it takes me to an oauth page where I select a server, once I select a server & select `Continue` it has the page where you select roles & it says at the bottom
```
Once you authorize, you will be redirected outside Discord to http://localhost:8123
```
The browser I'm on is a different machine, so localhost:8123 isn't the right place but I have no way to do this on a machine that will be localhost.

**Comment by LostOnTheLine** [comment]
The only place I can edit the redirect URL is the `https://discord.com/developers/applications` page but if I do that, pointing to the IP of the server, it gives me `Invalid OAuth2 redirect_uri`

**Comment by LostOnTheLine** [comment]
Why isn't there a simple Discord Webhook option? 

I don't need a bot, just to post events to Discord

**Comment by farukaydin** [comment]
@LostOnTheLine, could you try overriding the `WEBHOOK_URL` env variable (docs: https://automatisch.io/docs/advanced/configuration) and let us know whether it solves your problem or not?

**Comment by LostOnTheLine** [comment]
> I'm have the same issue and overriding the variable makes no different @farukaydin

With some help via Reddit/Discord I was able to find the variable that needs to be changed to make this work

```yaml
    environment:
      - HOST=localhost
      - PROTOCOL=http
      - PORT=8123
      - WEB_APP_URL=http://192.168.2.222:8123
...
...
    ports:
      - '8123:8123'
```

I included the port because if you change the port you have to change the `PORT=` variable as well as both sides of the Port mapping & include the address with the new port in the `WEB_APP_URL=` variable. I was told the Docs have been edited to be clearer & there's a suggested change to include that in the interface as a hint
