### ISSUE TITLE
 Action is incorrectly formed if there is RSS from YouTube

### ISSUE THREAD

**Issue by miqonee** [automatisch/automatisch#1175]
If you create an RSS trigger with a link to YouTube rss, and add automatic message body, then not all of them work correctly. Or rather, they work out so badly that only 2-3 (From useful ones) work.

example:
message text
![image](https://github.com/automatisch/automatisch/assets/108046712/19e21228-70a7-4268-aee6-c5b4cf487c2c)

result in Ntfy;
![image](https://github.com/automatisch/automatisch/assets/108046712/3281e441-d113-47b3-9391-135dde05f3c5)

 and in Telegramm:
![image](https://github.com/automatisch/automatisch/assets/108046712/8b4252c8-0e9b-4779-b1c5-a9e4d0442c13)

**Comment by barinali** [comment]
Hey @miqonee, thanks for reporting this bug! I think it happens due to the usage of `:` in variable paths. We'll take a look at it and possibly introduce a fix.

**Comment by miqonee** [comment]
I'm glad that you noticed, in general it is very interesting to observe the development of the project, I hope this error will be fixed
