### ISSUE TITLE
The "AdditionalFields" field does not work in the forms of the section with triggers.

### ISSUE THREAD

**Issue by Anto-MSHK** [automatisch/automatisch#1206]
When trying to create additional fields (both through dynamic fields and directly) in the index files of triggers, the assigned function is not called or statically assigned fields are not created.

But, when writing the same code in the action files, everything works correctly.

Tested on the Slack plugin. In the action called "send-a-direct-message" there are additional fields with a dynamic call. I created a test trigger in this plugin and the same code does not work.

**The following code in the test trigger does not work correctly:**
```
import defineTrigger from '../../../../helpers/define-trigger';
import test from './test';

export default defineTrigger({
	name: 'test',
	key: 'newTest',
	pollInterval: 15,
	description: 'Triggered when test.',
	arguments: [
		{
			label: 'Send as a bot?',
			key: 'sendAsBot',
			type: 'dropdown' as const,
			required: false,
			value: false,
			description:
				'If you choose no, this message will appear to come from you. Direct messages are always sent by bots.',
			variables: true,
			options: [
				{
					label: 'Yes',
					value: true,
				},
				{
					label: 'No',
					value: false,
				},
			],
			additionalFields: {
				type: 'query',
				name: 'getDynamicFields',
				arguments: [
					{
						name: 'key',
						value: 'listFieldsAfterSendAsBot',
					},
					{
						name: 'parameters.sendAsBot',
						value: '{parameters.sendAsBot}',
					},
				],
			},
		}
	],

	async run($) {
		await test($);
	},
});
```
_Again, in the action file (send-a-direct-message) of the same plugin, everything works correctly._

**Comment by barinali** [comment]
Hey @Anto-MSHK, thanks for pointing this out. I've prepared a fix for this in #1209 and merged it with our tests. Could you confirm the fix on your end?
