### ISSUE TITLE
Issue with the google sheet integration

### ISSUE THREAD

**Issue by umizoomi** [automatisch/automatisch#1365]
Hey all. I am excited to use automatisch for automating all kind of things. 

So I started to play around with sending SMS information from my android phone, to my automatisch instance and then saving that SMS in a google sheet.

I run against this issue however. It seems that when my flow is published. The settings regarding the google sheets action seems to get lost once its published. Preventing the execution of the Google Sheet action. The execution log still says the execution is succesfull. But no data gets added to the selected sheet after publishing

Before publishing the flow and selecting the Google Drive account, sheet file, worksheet, and then executing the test action, automatisch successfully updated the google sheet with a new row. 

When opening the published flow and opening the "Set up action" dropdown, I get an error. See screenshots and console log attached below.

![flow_inspect_after_publish](https://github.com/automatisch/automatisch/assets/4329209/524924f9-ca49-4e13-9de5-1a9563c2dc09)

[automatisch-1697718995224.log](https://github.com/automatisch/automatisch/files/13042790/automatisch-1697718995224.log)

**Comment by farukaydin** [comment]
@umizoomi thanks for the feedback. I will take a look and get back to you.

**Comment by umizoomi** [comment]
Thanks @farukaydin, Let me know if you want additional information. Or perhaps a video of what I'm describing

**Comment by farukaydin** [comment]
@umizoomi I debugged the problem locally and figured out that that was one of the problems we fixed on the main branch. We didn't release a new version after the fix, but it will be solved with the next version.

**Comment by umizoomi** [comment]
@farukaydin alright, I'll take a look at setting up an environment on the master branch ;)
