### ISSUE TITLE
Deployment through Coolify

### ISSUE THREAD

**Issue by art-n** [automatisch/automatisch#1386]
Does anyone already tried to deploy Automatisch through a Coolify installation (Heroku like) ?

`Error response from daemon: driver failed programming external connectivity on endpoint clo5lgsv4006tqra6o56fhbgj-main (b33899d008987e9a0f07bf7eed2aebfc77e4e77e5239c4cad69d212e648735aa): Bind for 0.0.0.0:3000 failed: port is already allocated`

**Comment by barinali** [comment]
Hey @art-n, have you made sure the port 3000 is available before the installation?

**Comment by art-n** [comment]
Hi @barinali, finally changed to 4000:3000 in docker-compose.yml and it works (:
