### ISSUE TITLE
Dynamic parent page on Notion Create Page action

### ISSUE THREAD

**Issue by falko100** [automatisch/automatisch#1409]
I want to use a variable to set the Parent page, so I can create pages within the page that triggers the flow.
Currently you need to select a static page that is the parent, but we have the dynamic ID available.
Can the Parent ID field be modified to allow text input with variables?

**Comment by barinali** [comment]
Hey @falko100, I appreciate your feedback!

As you realized, we have already merged a branch to improve the parent page field. It'll be available along with the next release unless you build a container out of the main branch.

**Comment by barinali** [comment]
Hey @falko100, I appreciate your feedback!

As you realized, we have already merged a branch to improve the parent page field. It'll be available along with the next release unless you build a container out of the main branch.
