### ISSUE TITLE
Snackbar always appears behind the chatbot icon in the production app

### ISSUE THREAD

**Issue by rohitrmenon** [automatisch/automatisch#1493]
ISSUE:As you can see in the images below, the snackbar always seem to appear behind the chatbot icon preventing readability of the entire message
-----------------
<img width="1440" alt="Screenshot 2023-12-15 at 5 26 08 PM" src="https://github.com/automatisch/automatisch/assets/131473060/47ba684e-622a-4c2a-bcaa-453e30d795ef">
<img width="1440" alt="Screenshot 2023-12-15 at 5 26 38 PM" src="https://github.com/automatisch/automatisch/assets/131473060/ac4007a0-861b-4951-b74a-2dbd2d2cf20a">

**Comment by barinali** [comment]
As we completely removed the chatbot, I'm closing this pull request.
