### ISSUE TITLE
Webhook + Discord works when clicking on Test Button but not work if published

### ISSUE THREAD

**Issue by douglasjunior** [automatisch/automatisch#1502]
_First of wall, thank you for the wonderful open-source tool! ❤️_

I have created a Flow using Webhook as Trigger and Discord as Action.

<img width="928" alt="image" src="https://github.com/automatisch/automatisch/assets/1512341/865fac18-3e1a-484e-ae51-f16f343afcc8">

When unpublished, I click on Webhook Test & Continue button and I can see the data received from Postman:

<img width="824" alt="image" src="https://github.com/automatisch/automatisch/assets/1512341/2a82fbc7-ee01-4721-bdc5-6912d7e5064f">

In the same way, when I click on Discord Test & Continue button, the message is received in the channel correctly.

<img width="812" alt="image" src="https://github.com/automatisch/automatisch/assets/1512341/25aaa769-b182-48eb-96d6-5166eb70479a">

<img width="310" alt="image" src="https://github.com/automatisch/automatisch/assets/1512341/a8d41559-4c5e-4a7c-b126-ba982d1e383a">

But, when I Publish the flow, it doesn't work anymore.

When I send a POST to the Webhook from Postman, I receive a 204 status code, but nothing is received on Discord. Not even the log is displayed on the Executions page.

What is I missing?

**Comment by farukaydin** [comment]
Hey @douglasjunior, thanks for the feedback.

Are you sure that your worker process is also running? To use Automatisch as expected, you need to have two different processes. One should serve the API and webhooks, and the other should execute the background jobs. You can get the more info here: https://automatisch.io/docs/guide/installation#docker

**Comment by douglasjunior** [comment]
Humm I didn't notice that.

When I read the docs I understand that the worker is necessary only if I want to create a cluster.

I will try again soon, thank you!
