### ISSUE TITLE
Use filter step on data from preceding webhook trigger and HTTP request action?

### ISSUE THREAD

**Issue by TyceHerrman** [automatisch/automatisch#1751]
Trying to create a workaround flow for the lack of "Update" or "Create or Update" options in the Hubspot integration.

I'm catching a webhook with an email address in the data and then using a HTTP request action to make a call to Hubspot contacts endpoint. 

In a subsequent Filter action, can I use the data from the HTTP request as part of the condition? So essentially is the email in the webhook equal to an email address in the HTTP request response?

**Comment by TyceHerrman** [comment]
Great! I had my http request set up incorrectly so I wasn't seeing the right data come through, but confirm that output fields from both webhook and http request were available on both sides of the filter condition.

I understood that there's no else/elif logic yet. As a workaround, could you have have two different flows fired by the same webhook? So in one flow, do x if webhook email and http request email are equal and in the other flow do y if webhook email and http request email are not equal

**Comment by barinali** [comment]
There is no common trigger between flows etc. However, you could set up a flow with a webhook which then fires two consecutive HTTP requests to two different Automatisch flows that have webhook triggers. So, that'd mean you create a separate flow to unify your webhook URL, but then split it within.

**Comment by TyceHerrman** [comment]
> two different Automatisch flows that have webhook triggers.

I think I follow you except for this part - I don't think I'd need additional webhook triggers in this implementation? 

Here's what I was thinking of doing:
<img width="389" alt="Screenshot 2024-03-20 at 11 34 35 AM" src="https://github.com/automatisch/automatisch/assets/22066434/d821f7a9-e022-47ab-83ef-8d7c8b3be2dc">

and here's how I think I'd go about implementing your suggestion on how to do this:
<img width="468" alt="Screenshot 2024-03-20 at 11 36 45 AM" src="https://github.com/automatisch/automatisch/assets/22066434/2f7f93a4-5668-4ea9-83a0-39e3579ea3d6">

I'm just not sure what webhook(s) I would use after the intial webhook in the second implementation. Seems like I could just use two trigger-less flows, no?

**Comment by barinali** [comment]
Since we don't support any sort of trigger-less flows, you'll need two trigger-ful flows that you can initiate with webhooks.

**Comment by TyceHerrman** [comment]
Got it. I think I was confusing having multiple actions in a flow without triggers as the ability to have a totally trigger-less flow. I think I'll have to do implementation I proposed in the first image then. Thanks for the help!

**Comment by barinali** [comment]
@TyceHerrman cheers.

I'm closing this issue as it's resolved.
