### ISSUE TITLE
v0.11.0 points to v0.10.0

### ISSUE THREAD

**Issue by benjaminvanrenterghem** [automatisch/automatisch#1860]
Hello

As reported on Discord, the Dockerfile.compose still points to v0.10.0 for tag v0.11.0.
https://github.com/automatisch/automatisch/blob/3932e554da97cd59f5191404561ed4b7d820353d/docker/Dockerfile.compose

Thanks

**Comment by farukaydin** [comment]
Hey @benjaminvanrenterghem,

This problem is solved on the main branch. I'm closing the issue, but please feel free to re-open it if you see any unexpected behavior.
