### ISSUE TITLE
"/docker/entrypoint.sh": not found during Render.com deployment

### ISSUE THREAD

**Issue by mattsjohnston** [automatisch/automatisch#1909]
When trying to deploy on Render.com, the automatisch-worker service is failing to deploy.

```plaintext
error: failed to solve: failed to compute cache key: failed to calculate checksum of ref
wrfrc9wj8mp01ckwrxe3k906l::y9j681802bmynrhabvic92umz: “/docker/entrypoint.sh”: not found
error: exit status 1
```

# Steps to Reproduce

1. Hit the Deploy on render button from the installation instructions page
2. Wait for deploy fail, and read logs

**Comment by barinali** [comment]
@mattsjohnston, we have fixed the render deployment file. Could you try it and let us know if it helps you?

**Comment by mattsjohnston** [comment]
That worked! Thanks
