### ISSUE TITLE
Problem with rendering in DynamicField component with long variables

### ISSUE THREAD

**Issue by jmas** [automatisch/automatisch#1933]
Field `dynamic` has problems with rendering long variables. Example in screenshot:

<img width="1191" alt="Знімок екрана 2024-06-13 о 03 18 05" src="https://github.com/automatisch/automatisch/assets/90701/4d67e372-a2a6-441f-bbab-b39fdb88f00e">

**Comment by barinali** [comment]
@jmas, thanks for your contribution! As we have merged your branch, I'm closing this issue as completed.
