### ISSUE TITLE
non-Docker Install

### ISSUE THREAD

**Issue by technomaji** [automatisch/automatisch#1946]
As a general rule I have not gotten into using Docker - one would have to trust that a total stranger's package is clean from malware ... that's not a secure approach.

Can one simply install Automatisch the good ol' fashion way ... I don't know what LANG you're using, but if you could just bullet the configuration you already have in your docker ENV, ja nun das wäre einfach super!

Look forward to taking your software for a spin  ;-)

**Comment by shadzik** [comment]
Reading the documentation didn't cross your mind? https://automatisch.io/docs/contributing/development-setup

**Comment by shadzik** [comment]
Sorry, I didn't want to be snarky or attack you in any way. Please read the documentation, it helped me to get automatisch running without Docker. Hope it will work for you as well! Good luck!

Btw. I'm not affiliated with automatisch, so give it a try despite my comment.

**Comment by kuba618** [comment]
Nothing but the link provided by @shadzik is helpfull.
You'd need to setup postgres (the one which best work for me is 14.5) and redis on your machine or have a connection to one.
It will also require to have node installed with preferably yarn.
Then you can go for the `yarn install` and .env setup by copying the .env-example and feeding your data there.
Take a look here, you can find some sample data https://github.com/automatisch/automatisch/blob/main/.devcontainer/boot.sh

**Comment by kuba618** [comment]
Hi @technomaji,
did you tried the steps I mentioned?
Cheers

**Comment by technomaji** [comment]
Thank you @kuba618 ,
I've had other priorities and not looked at this for a while. I'll take a look again when time permits. Appreciate your pointers  ;-)
