### ISSUE TITLE
RSS error for microsoft research blog

### ISSUE THREAD

**Issue by gc1423** [automatisch/automatisch#1949]
automatisch throws the following error when adding microsoft research blog RSS: Cannot read properties of undefined (reading 'toString')

the rss feed: https://www.microsoft.com/en-us/research/feed/

![image](https://github.com/automatisch/automatisch/assets/16733725/95d9bcce-97f6-4a1e-8c46-1f51a987def8)

**Comment by jmas** [comment]
@gc1423 Tested, for me it works. Do other feeds works?

<img width="876" alt="Знімок екрана 2024-07-11 о 13 15 15" src="https://github.com/automatisch/automatisch/assets/90701/02b93d05-a7c7-47fd-908d-6c1668bee279">

**Comment by gc1423** [comment]
> @gc1423 Tested, for me it works. Do other feeds from other websites works?
> 
> <img alt="Знімок екрана 2024-07-11 о 13 15 15" width="876" src="https://private-user-images.githubusercontent.com/90701/347778494-02b93d05-a7c7-47fd-908d-6c1668bee279.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMDU3NTQsIm5iZiI6MTcyMTMwNTQ1NCwicGF0aCI6Ii85MDcwMS8zNDc3Nzg0OTQtMDJiOTNkMDUtYTdjNy00N2ZkLTkwOGQtNmMxNjY4YmVlMjc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDEyMjQxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkZDMxODQxMmY3NGU3ZjdjYWMwMTQ2YWRiZTE2NWUxOGY2MTJjNzQ1OWU4NjFiYTE3NzUxNGQxNzQwMDI5NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.N-MkQMuAd78I3IuSqAg_DYKn0CXhW4KCoVx7B1C4rB8">



Thanks for your reply. 

Now it works, and I did nothing. Strange...
