### ISSUE TITLE
Prebuilt docker images

### ISSUE THREAD

**Issue by ksurl** [automatisch/automatisch#720]
Currently the compose file builds locally before running the containers. consider pushing a public image to Docker Hub and/or GitHub Container registry for the main and worker images.

GitHub actions can build and push on new releases/tags and commits for versioned and branch tags (v0.2.0, latest, main)

**Comment by barinali** [comment]
Thanks for the suggestion. We will introduce docker images as soon as possible.

**Comment by esturniolo** [comment]
+1

**Comment by barinali** [comment]
We have published an image on Docker hub (automatischio/automatisch:0.2.0) and GitHub container registry (automatisch/automatisch:0.2.0)! 🎉 We'll keep releasing new versions for Docker along with npm releases.

We have yet to write documentation for the standalone image (#750). However, curious ones can already play with it!
