### ISSUE TITLE
docker issue: postgres db does not exist

### ISSUE THREAD

**Issue by ksurl** [automatisch/automatisch#723]
`2022-11-18 16:09:24.340 UTC [66] FATAL:  database "automatisch" does not exist`

It seems like the container does not create a db if one doesn't exist on 1st startup.

also missing volume mounts for redis and postgres so I added those

postgres: /var/lib/postgresql/data and redis: /data

**Comment by barinali** [comment]
Could you prodive us with the exact reproduction steps? By default, the postgres image used in the docker compose definition should create the database.

**Comment by ksurl** [comment]
looks like it may have been permission issue on the folder. I deleted it and let it create itself. It creates the db now, but if you set a password, the automatisch image startup script connects without auth and fails.

**Comment by ksurl** [comment]
There's a typo in `wait-for-postgres.sh`. The database name argument uses the database host instead of the name environment variable. I fixed it locally and rebuilt and it works. This matters if the db host name does not match db name.
