### ISSUE TITLE
APP_SECRET_KEY and ENCRYPTION_KEY in docker image

### ISSUE THREAD

**Issue by ksurl** [automatisch/automatisch#725]
These are generated and written to /automatisch/storage/.env in the Dockerfile. This folder is overwritten when mounted at compose runtime, so it exits with error .env file does not exist. This should be generated at container start if not specified as an environment variable.

Suggestion: change `CMD` to an entrypoint script that checks for environment variables before autogenerating the variables with `openssl rand` and then starting the service.

**Comment by barinali** [comment]
I think this is tackled via #727. So, I am closing this issue. Thanks, @ksurl!
