### ISSUE TITLE
Replace wait for postgres logic with healthcheck in postgres service

### ISSUE THREAD

**Issue by barinali** [automatisch/automatisch#735]
To have a leaner docker image, we'd like to introduce a healthcheck definition in postgres service in the docker-compose.yml file that main and worker services depend on. In this way, we can remove the sleep logic for postgres readiness in the entrypoint script and `postgresql-client` installation in the Dockerfile.

reference: https://github.com/peter-evans/docker-compose-healthcheck

**Comment by barinali** [comment]
@ksurl, would this be something you are interested in tackling? Otherwise, I'd take it on.

As you are contributing to Automatisch without having planned issues, I thought I would ask you first, just in case. Also, I appreciate your interest and contribution here once again!

**Comment by ksurl** [comment]
sure. I'll submit a PR and continue discussion there.

**Comment by barinali** [comment]
@ksurl I see that this issue is not auto-closed because of the way how it's linked. If you use one of the keywords mentioned in [here](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword), the relevant issue would automatically be closed once the corresponding pull request is merged.

Thanks for your contribution once again!
