### ISSUE TITLE
Use alpine version of node:16 in Dockerfile

### ISSUE THREAD

**Issue by barinali** [automatisch/automatisch#738]
We have initially not used the alpine version of node:16 for tooling convenience. However, resolving #735 will enable us to switch to the alpine version.

For the sake of image size, we'd like to use `node:16-alpine`.

**Comment by barinali** [comment]
@ksurl, giving you a shout here as it may pique your interest.

**Comment by ksurl** [comment]
read my mind. I tested a local build and it seems to start without obvious errors.

**Comment by barinali** [comment]
I'd say the main build. We may later introduce one with arm64 architecture for multiple images, as there was some demand for it in the /r/selfhosted post. However, before introducing that one, we may like to automatize the release process per the docker hub and GitHub container registry.

**Comment by barinali** [comment]
I am closing this issue as we have merged #739 by @ksurl.
