### ISSUE TITLE
Iterate Dockerfile for release

### ISSUE THREAD

**Issue by barinali** [automatisch/automatisch#742]
We need to iterate the Dockerfile for a leaner release. Right now, it has dos2unix and token generation logic in place. These two pieces are not something we expect in the Dockerfile we build and push to registries as we think they are not needed. However, while doing this, we also need to keep the functionality provided for docker-compose in place.

**Comment by barinali** [comment]
@ksurl I thought I would bring this to your attention again to see if you'd like to tackle it.

**Comment by ksurl** [comment]
We can cut dos2unix once it's published to a public registry.

not sure how to handle the keys. just remove it and leave it to the user to generate their own? exit if none specified in environment variables on first run?

**Comment by barinali** [comment]
> We can cut dos2unix once it's published to a public registry.

Sure, it should be fine.

> not sure how to handle the keys. just remove it and leave it to the user to generate their own? exit if none specified in environment variables on first run?

We already have such logic on the application level for the `ENCRYPTION_KEY`; later, we may introduce one for the `APP_SECRET_KEY` environment variable as well. So, no need to introduce that on the docker level.
