### ISSUE TITLE
Fix RSS Error for Google News

### ISSUE THREAD

**Issue by slavakurilyak** [automatisch/automatisch#836]
automatisch v0.3.0 throws the following error when adding Google News RSS:

`insert into "executions" ("created_at", "flow_id", "internal_id", "test_run", "updated_at") values ($1, $2, $3, $4, $5) returning "id" - value too long for type character varying(255)`

Here's the RSS feed for 'chatgpt' on Google News:

https://news.google.com/rss/search?q=chatgpt&hl=en-US&gl=US&ceid=US:en

Here's 'chatgpt' on Google News:

https://news.google.com/search?q=chatgpt&hl=en-US&gl=US&ceid=US:en

<img width="867" alt="error" src="https://user-images.githubusercontent.com/6625584/211661183-1b60f03f-7a54-4c31-bbf2-f15909d1a725.png">

<img width="1282" alt="screenshot" src="https://user-images.githubusercontent.com/6625584/211661188-d5379987-bd73-44dd-a34e-8060d2633f66.png">

Here's the error log:

```
/flows:1 Denying load of chrome-extension://gacgndbocaddlemdiaadajmlggabdeod/injectedScript.bundle.js. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.
chrome-extension://invalid/:1          Failed to load resource: net::ERR_FAILED
index.ts:71 Uncaught (in promise) Error: insert into "executions" ("created_at", "flow_id", "internal_id", "test_run", "updated_at") values ($1, $2, $3, $4, $5) returning "id" - value too long for type character varying(255)
    at new t (index.ts:71:5)
    at QueryManager.ts:246:15
    at n (asyncMap.ts:30:30)
    at asyncMap.ts:19:47
    at new Promise (<anonymous>)
    at Object.then (asyncMap.ts:19:16)
    at Object.next (asyncMap.ts:31:39)
    at Xo (module.js:132:18)
    at Jo (module.js:176:3)
    at t.next (module.js:225:5)
```

**Comment by barinali** [comment]
@slavakurilyak, is this consistently reproducible on your side? Unfortunately, when I test a flow with the given RSS feed, I cannot reproduce it.

**Comment by slavakurilyak** [comment]
I tested this RSS link again and it worked. I am no longer able to reproduce this.
