### ISSUE TITLE
Why poll interval input is disabled here?

### ISSUE THREAD

**Issue by drgnchan** [automatisch/automatisch#864]
I am just curious about why poll interval input is disabled here?

https://github.com/automatisch/automatisch/blob/85a35580741b77cad998fd2d740814c635bbb25f/packages/web/src/components/ChooseAppAndEventSubstep/index.tsx#L245-L254

**Comment by barinali** [comment]
Hey @drgnchan, as the feature is not completely defined yet and the API does not support dynamic intervals, we display that input only for informative purposes.

We will introduce the capability of dynamic intervals, but it's difficult to predict when it will be available.

**Comment by drgnchan** [comment]
Thankyou!Now I understand. @barinali
