### ISSUE TITLE
Webhook URL of custom web hook action

### ISSUE THREAD

**Issue by pareeohnos** [automatisch/automatisch#878]
I'm creating a couple of new apps to integrate with one another, and they're both going to have web hook based triggers. One of these is straightforward as I can register the webhook programmatically, however one of them I can't do this so I need to know the webhook URL. According to the documentation for the existing webhook app, it should be shown in the "test" step when creating f low but this doesn't seem to apply to our own apps.

I've done a little digging and it seem related to this snippet of code (src/models/step.ts):

```typescript
  get webhookUrl() {
    if (this.appKey !== 'webhook') return null;

    const url = new URL(`/webhooks/${this.flowId}`, appConfig.webhookUrl);
    return url.toString();
  }
```

`this.appKey` is only ever going to be `'webhook'` for that one built in app, so it is impossible (as far as I can tell) to get the webhook URL from the UI. Instead I feel that this function should check if the trigger type is a webhook rather than the appKey, then it would work for any custom app

**Comment by barinali** [comment]
Hey @pareeohnos, thanks for raising this topic.

We have had the assumption that we would only need to show the webhook URL for integrations where we cannot programmatically register the webhook. However, as far as I understand, you're writing an integration where you'd like to show it to the user so that they can register it.

Could you elaborate on your use case (as well as the provider) so I could see if we'd like to provide a separate functionality to show webhook URLs, regardless of the app/event key or so? For example, do you plan to introduce some options/arguments for the trigger?

**Comment by pareeohnos** [comment]
I'd agree with your assumption, but that's what I'm trying to do. I've created a new app (for a system called Practitest) and in that I've created a couple of triggers, both of which are of the "webhook" type, however I have not found anywhere on their system that allows me to programmatically register those webhooks - I have to manually add them in their platform.

I suppose I'm using automatisch in a slightly unconventional way as I want two specific systems to integrate, so rather than making these apps generic so anything could use them, I may well have some slightly more specific code in there. 

But lets say for example in my trigger, I get notified that an "Issue" has been updated but the webhook may not include all of the data that I need to know about, it's just a notification afterall. So in my trigger I'm going to make an API request to fetch additional information and then that would get passed on to the actions. I can't do this using the generic "webhook" app that ships with Automatisch hence I'm rolling my own, however I have no easy way of getting my webhook URL to register in Practitest.

**Comment by barinali** [comment]
> I may well have some slightly more specific code in there.

I'm unsure how this can be achieved within our current webhook implementation. I cannot think of a way to enhance the payload that comes from the webhook request **within** the webhook-typed trigger integration. In this scenario, I could suggest something like below;

1. Configure the trigger with custom webhook integration 
2. Register the given webhook URL manually on Practitest
3. Configure an action to find the associated data (I expect that you'd write an action to "find an issue") **<--** this is the part I'd expect your flow's data will be enhanced as you like
4. Arrange the rest of the flow up as desired.

How does this sound to you?

**Comment by pareeohnos** [comment]
So in that sense, I'd essentially make the practitest app triggerless, and instead have multiple actions used in the pipeline? I suppose that could work yeah - and I assume that if you have multiple actions in a flow that each output can be passed on to the next action?

**Comment by pareeohnos** [comment]
Brilliant thanks, I'll give that a shot then 🙂

**Comment by barinali** [comment]
I'll go ahead and close this issue now. However, feel free to follow up on the matter if you need to, @pareeohnos.

**Comment by TyceHerrman** [comment]
@barinali I think I'm facing a similar issue and would like your suggestion on how to handle it. I'm trying to wire together contact properties update in my Hubspot CRM to update custom fields in Beehiiv. I'm thinking about setting up a webhook integrated with Hubspot on the trigger side and an http request to Beehiiv on the action side. However, the hubspot application requires a target url, but the custom webhook url from Automatisch isn't visible until after testing the connection, but that requires setting the target url in hubspot and I'm stuck in this chicken/egg loop. 
<img width="1208" alt="Screenshot 2024-03-13 at 4 35 13 PM" src="https://github.com/automatisch/automatisch/assets/22066434/9f1ba231-60c5-419c-9b47-7b5cf9af9450">


Am I thinking about this the right way? Could this also be set up as multiple trigger-less actions? I feel like I'm close but can't quite wrap my head around how to implement this. Thanks!

**Comment by barinali** [comment]
@TyceHerrman this sounds like you should be able to utilize our webhook integration with the custom raw webhook event. In this way, you'll see the webhook URL from Automatisch and you can use it on Hubspot webhooks.

![image](https://github.com/automatisch/automatisch/assets/1263419/b95fc1ae-1980-4476-a211-b4b40893708e)

You should provide this URL to the target URL field. Once you receive some events on the webhook URL from Automatisch, you can click "test & continue" to see the payload you receive from Hubspot.
