### ISSUE TITLE
Reddit connection?

### ISSUE THREAD

**Issue by farukaydin** [automatisch/automatisch#908]
### Discussed in https://github.com/automatisch/automatisch/discussions/773

<div type='discussions-op-text'>

<sup>Originally posted by **Starttoaster** December  4, 2022</sup>
This is a feature request for a new connection type. What I'm imagining is a reddit connection that connects with the reddit API and allows you to watch a subreddit for new posts. Potentially, this could also filter and only trigger on posts where the title contains some user-defined string.

Reddit allows you to create oauth2 apps to use their API, which seems like would help to accomplish this. 

This seems like it would be useful for, say, companies with a presence on reddit, which seems more and more common for tech companies. It would also be useful for people that use some of the trading subreddits like /r/hardwareswap.</div>

Existing upvote count from GitHub discussions: 2

**Comment by ralyodio** [comment]
the docs don't list reddit, is it supported? I want to do rss to reddit.

**Comment by barinali** [comment]
@ralyodio, we seem to have missed documenting it. However, it indeed exists. You may only create a link post so far as an action. Does that suffice your scenario? If not, I'd suggest you create an issue for us to implement what you may need as an action.
