### ISSUE TITLE
Ghost

### ISSUE THREAD

**Issue by farukaydin** [automatisch/automatisch#915]
### Discussed in https://github.com/automatisch/automatisch/discussions/822

<div type='discussions-op-text'>

<sup>Originally posted by **DanHakimi** December 30, 2022</sup>
An integration into a Ghost blog that would work with on publish events and stuff like that would be cool.

https://ghost.org/</div>

Existing upvote count from GitHub discussions: 4

**Comment by rusty1281** [comment]
Would like an official support for Ghost as well!

**Comment by farukaydin** [comment]
@rusty1281, thanks for the feedback. Ghost is on our list for the following integrations. No promise about the time, but hopefully we will deliver it soon.

**Comment by rusty1281** [comment]
I see this integration has been added, great job! Any eta on the documentation update? How to exactly implement this?

Thank you again!

**Comment by barinali** [comment]
@rusty1281, it'll ideally appear on public documentation and be available in the application when we make a new release. However, you may already check out [the connection](https://github.com/automatisch/automatisch/blob/main/packages/docs/pages/apps/ghost/connection.md) and [triggers documentation page](https://github.com/automatisch/automatisch/blob/main/packages/docs/pages/apps/ghost/triggers.md)s in the repository here to see how to connect your Ghost instance with Automatisch and what's available for triggers.

**Comment by rusty1281** [comment]
> @rusty1281, it'll ideally appear on public documentation and be available in the application when we make a new release. However, you may already check out [the connection](https://github.com/automatisch/automatisch/blob/main/packages/docs/pages/apps/ghost/connection.md) and [triggers documentation page](https://github.com/automatisch/automatisch/blob/main/packages/docs/pages/apps/ghost/triggers.md)s in the repository here to see how to connect your Ghost instance with Automatisch and what's available for triggers.

Excellent! Thank you! Will give it a go.

**Comment by rusty1281** [comment]
Hi again! I have Automatisch running behind a reverse proxy, all good, but I have some questions about this integration. Specifically these steps:

4. Add your Admin API Key in the **Admin API Key** field on Automatisch.
5. Add your API URL in the **Instance URL** field on Automatisch.

Where are exactly admin api key and instance url fields inside automatisch? Thank you!
