### ISSUE TITLE
Google Sheet

### ISSUE THREAD

**Issue by farukaydin** [automatisch/automatisch#918]
### Discussed in https://github.com/automatisch/automatisch/discussions/828

<div type='discussions-op-text'>

<sup>Originally posted by **Vick14asking** January  6, 2023</sup>
Hi, wondering if anyone could help me out. 

I would like to know how upon selecting a specific option from the drop down list, I could trigger another column, also with drop down list to appear. 

I am relatively new to using the google sheet too. Seeking guidance. 

Thank you in advance!

Vicky</div>

Existing upvote count from GitHub discussions: 0

**Comment by barinali** [comment]
I'm closing this issue as it's already released in a previous version. Feel free to create a new issue for any specific actions and/or triggers.
