### ISSUE TITLE
Postgres integration

### ISSUE THREAD

**Issue by farukaydin** [automatisch/automatisch#923]
### Discussed in https://github.com/automatisch/automatisch/discussions/858

<div type='discussions-op-text'>

<sup>Originally posted by **Franchise712** January 20, 2023</sup>
It would be great to have an integration with postgres as well! Great product!</div>

Existing upvote count from GitHub discussions: 4

**Comment by shehabghazy** [comment]
hey @farukaydin, Hpoe you are doing well

the link which refers to the discussion returns 404. I'm working now on an integration for postgres. If there is any requirements or important info have been mentioned in the discussion, may you mention them here to have an idea ?
I'm working on specific 3 methods: insert, update and delete.
And also the execution of normal sql query

**Comment by farukaydin** [comment]
Hey @shehabghazy, we disabled the GitHub discussions entirely (with writing comments to keep the discussion members updated) because we realized that some community members skipped checking the discussion board. So it's going to be more visible with the issues.

We don't have any specific requirements for the PostgreSQL integration, but splitting the integration into small tasks like auth, insert, update, and delete parts and creating different PRs for them would be better to review.

Having a unique identifier for the records might be difficult, you can check [here](https://github.com/automatisch/automatisch/blob/main/packages/backend/src/apps/rss/triggers/new-items-in-feed/new-items-in-feed.ts#L12) to see how we deal with those situations.

**Comment by shehabghazy** [comment]
Hey @farukaydin, thanks for yourclarification..

I have created a PR for the postgres integration:
https://github.com/automatisch/automatisch/pull/1076

Excuse me it was some difficult to split the integration into small tasks becasueI had already worked on it and finished most of its parts before this discussion.
I think you will find it clear and it will not take a big effort to review, if everything goes well I can begin to document it.

**Comment by barinali** [comment]
I'm closing this issue as PSQL integration is already released. Feel free to create new issues for specific actions and/or triggers.
