### ISSUE TITLE
Spotify Integration

### ISSUE THREAD

**Issue by farukaydin** [automatisch/automatisch#928]
### Discussed in https://github.com/automatisch/automatisch/discussions/871

<div type='discussions-op-text'>

<sup>Originally posted by **markthom-as** February  1, 2023</sup>
It would be wonderful to be able to automate playlist creation a la Zapier!</div>

Existing upvote count from GitHub discussions: 3

**Comment by barinali** [comment]
I'm closing this issue as it's already released in a previous version. Feel free to create a new issue for any specific actions and/or triggers.

Kudos to @zntemel for your contributions!
