### ISSUE TITLE
MacOS Error

### ISSUE THREAD

**Issue by m-thomson** [automatisch/automatisch#950]
Fresh install on MacOS 13.2.1 with an Apple Silicon Mac results in error `Error: Not Authorised!`
when browsing to the app at port :3000

<img width="472" alt="CleanShot 2023-02-20 at 16 19 17@2x" src="https://user-images.githubusercontent.com/5273016/220216862-a22bab98-ee22-4c32-8e15-c3fc2a966446.png">

See log for details
[automatisch-log.txt](https://github.com/automatisch/automatisch/files/10788526/automatisch-log.txt)

**Comment by m-thomson** [comment]
<img width="1116" alt="CleanShot 2023-02-20 at 16 28 02@2x" src="https://user-images.githubusercontent.com/5273016/220217414-eaf03bdf-1773-4f60-8272-059e1728b1a5.png">

**Comment by farukaydin** [comment]
@m-thomson thanks for the feedback. We're planning to fix this issue with the next release. Meanwhile could you clear your local storage and try to use [https://localhost:3000/login](https://localhost:3000/login) page

**Comment by pablodz** [comment]
same error here, thanks for answer

**Comment by fathermahoney** [comment]
Having the same issue

**Comment by rsaisankalp2** [comment]
having same issue

**Comment by farukaydin** [comment]
This issue is resolved with the current release of Automatisch(v0.6.0). I will close this issue, but please let us know if you see any misbehavior wrt this issue.
