### ISSUE TITLE
Multiple wokrers

### ISSUE THREAD

**Issue by ahmedrshdy** [automatisch/automatisch#963]
Hi guys,

Thanks for the exceptional effort to make such a great tool public. My question is about scaling for production, is it possible to add multiple workers so load is distributed among multiple workers when there are many running flows concurrently?

Cheers

**Comment by farukaydin** [comment]
Hey @ahmedrshdy, thanks for your kind words.

We designed Automatisch's architecture in a way that workers can scale horizontally. Redis handles the communication between the main instance and workers. We couldn't find a problem while testing horizontally scaled workers. Another concern, which is rather out of Automatisch's scope, but If you scale the workers horizontally, that can consume the API limits greedily. Let me know if you need anything else for horizontally scaling the workers. (You can contact me on Discord if you have any questions.)

**Comment by ahmedrshdy** [comment]
@farukaydin thanks for the prompt response

`that can consume the API limits greedily`, I think you refer to exhausting the API integration, am I correct?

**Comment by farukaydin** [comment]
@ahmedrshdy I mean the API limits (that are bound to time duration) of the third-party services. You will send the same amount of requests regardless of the number of workers, but sending them concurrently with multiple workers will consume the limits faster in a specific period of time. It might be problematic if the API allows you to send X amount of requests in Y minutes.

**Comment by ahmedrshdy** [comment]
@farukaydin got it, it is clear now. Thank you
